script: bash ./deploy.sh
language: php
php:
- 5.5
env:
  global:
  - GH_REF: github.com/UDOOboard/Bricks-Docs.git
  - secure: NGLH0ysDwT1xpG2HZ6bnPkDrkfEzuRVDS5EEZGL/zgp+nwzlreaBZjYv1a/FfqJPWATauDVIRSrY8UJyj95eabHgDwDRaq6R2Wp08sq4k+I3trhahoxtvnyfx3Udxuglcr5oIzv79JxNfPlE2iQP6RB/k/K0/sAESFNMD/ClokZgRDw+2LXYCUu1HqLiESsTbl+wEtFGucaUoVQJ3u3sy0pPoNf7L/lcsqiJv5pOMBhJf5dceUtCGksupdoJxjwMI+0Qw7XQAQOVUytrRjTKjyYf6PZEkskVXku+qHwG3xnvbO/MgTaYGFD3afC/pvGTCl0/Vcc6CUGPAVR+dy8vL2yUM/aJ8BRdfFIVkLRAXAhSv6cQKVz36auaZwtRXNQpzgVrSQAfmBMSu/mB4HjfKwRuTfLYC6HKldGZnITybKE7QLN5oYZ7BrOC3fQi+h/hBld9tJo87qAhAN7mVBm+D3MI5a+U0pQy7EmU1+ztnnKb0+Xq1vf7LyhcCK+e9ZxZ25iLixGGa1QVmNLmRwIO/eIuLzVt2MxBBfz7xVdBhMGXaQCmo2Ht08H2PQOXJVBVWSrZFDPhEehXNppeNkQiel1Ut/moR5ArOTNUCViK0ofzHdjd0du9ySya5W3qRM1mUpg/v6ce8grjmx5/dlbwWHXX4QMITTfzd6if4uPVCS4=
